apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/dev-frontend
  newName: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/dev-frontend
  newTag: abc
resources:
- ../../base

# patchesStrategicMerge:
# - fe-deployment-patch.yaml
# - fe-service-patch.yaml