apiVersion: apps/v1
kind: Deployment
metadata:
  name: maskapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maskapi
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: maskapi
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.20.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: NotIn
                values:
                - dev_gpu_node_group 
      containers:
        - name: maskapi
          env:
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
          image: 068251041443.dkr.ecr.ap-northeast-2.amazonaws.com/dev-mask-api:57975de7a59e74cafd8afd41c80d6d06e2f9d62a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: properties
              mountPath: /app/config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: properties
          secret:
            secretName: mask-api-properties
      
