apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-deploy
  labels:
    app: api-test
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: api-test
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: api-test
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.20.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - prod_gpu_node_group
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api-test
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: stable-diffusion
        image: gadicc/diffusers-api
        ports:
          - containerPort: 8000
      - name: api-demo
        env:
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_IAST_ENABLED
            value: "true"
        image: 068251041443.dkr.ecr.ap-northeast-2.amazonaws.com/prod-api:db5c710de70273ec9050f31a6b3cc191c73298e9
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: properties
            mountPath: /app/config
      volumes:
        - name: backnginx-config
          configMap:
            name: backnginx-config
        - name: properties
          secret:
            secretName: stable-diffusion-properties





# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: api-test-deploy
#   labels:
#     app: api-test
# spec:
#   selector:
#     matchLabels:
#       app: api-test
#   template:
#     metadata:
#       labels:
#         app: api-test
#         admission.datadoghq.com/enabled: "true"
#       annotations:
#         admission.datadoghq.com/java-lib.version: v1.20.1
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: eks.amazonaws.com/nodegroup
#                 operator: In
#                 values:
#                 - prod_gpu_node_group   
#       containers:
#       - name: stable-diffusion
#         image: gadicc/diffusers-api
#         ports:
#           - containerPort: 8000
#       - name: api-demo
#         env:
#           - name: DD_PROFILING_ENABLED
#             value: "true"
#           - name: DD_LOGS_INJECTION
#             value: "true"
#           - name: DD_APPSEC_ENABLED
#             value: "true"
#           - name: DD_IAST_ENABLED
#             value: "true"
#         image: 068251041443.dkr.ecr.ap-northeast-2.amazonaws.com/prod-api:db5c710de70273ec9050f31a6b3cc191c73298e9
#         ports:
#         - containerPort: 8080
#         volumeMounts:
#           - name: properties
#             mountPath: /app/config
#       volumes:
#         - name: backnginx-config
#           configMap:
#             name: backnginx-config
#         - name: properties
#           secret:
#             secretName: stable-diffusion-properties
