apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-test-deploy
  labels:
    app: api-test
spec:
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - dev_gpu_node_group   
      containers:
      - name: stable-diffusion
        image: gadicc/diffusers-api
        ports:
          - containerPort: 8000
      - name: api-demo
        image: 068251041443.dkr.ecr.ap-northeast-2.amazonaws.com/dev-api:ce398cf6cd6fa4aa27e363bd399eccaa11e31c51
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: properties
            mountPath: /app/config
      volumes:
        - name: backnginx-config
          configMap:
            name: backnginx-config
        - name: properties
          secret:
            secretName: properties
