apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-test-deploy
  labels:
    app: api-test
spec:
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.20.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - dev_gpu_node_group   
      containers:
      - name: stable-diffusion
        image: gadicc/diffusers-api
        ports:
          - containerPort: 8000
      - name: api-demo
        env:
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_IAST_ENABLED
            value: "true"
        image: 068251041443.dkr.ecr.ap-northeast-2.amazonaws.com/dev-api:4885554f0c31342cf748e5bcfcdf243f06d2dab8
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: properties
            mountPath: /app/config
      volumes:
        - name: backnginx-config
          configMap:
            name: backnginx-config
        - name: properties
          secret:
            secretName: stable-diffusion-properties
